# -*- coding: utf-8 -*-
r"""Emits ``our_prem.h``, this library's PREM as a C header.

The three compiled drivers beside this file have to evaluate the *same*
density profile as :func:`earth.density_prem`, or the comparison measures
Earth models rather than propagation.  Transcribing forty coefficients by
hand is exactly the kind of step that fails silently, so the header is
generated from ``earth._PREM_COEFFS`` instead.

Run it from the repository root::

    python tests/external_drivers/gen_prem_header.py > our_prem.h

The result reproduces ``earth.density_prem`` to 5e-14 over 6372 radii,
which ``nufast_drv --profile`` re-checks.
"""

import os
import sys

import numpy as np

sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.abspath(__file__)))), 'src'))

import globaldefs as gd                                       # noqa: E402
import earth                                                  # noqa: E402


def main():
    boundaries = np.asarray(earth.PREM_BOUNDARIES, dtype=float)
    coefficients = np.asarray(earth._PREM_COEFFS, dtype=float)

    lines = [
        '// Generated by tests/external_drivers/gen_prem_header.py.',
        '// This library\'s PREM, emitted from earth._PREM_COEFFS so that no',
        '// digit is transcribed.  Do not edit by hand.',
        '#ifndef OUR_PREM_H',
        '#define OUR_PREM_H',
        '',
        'static const double OUR_EARTH_RADIUS = %.17g;' % gd.EARTH_RADIUS,
        'static const int OUR_PREM_NB = %d;' % boundaries.size,
        'static const double OUR_PREM_B[%d] = {%s};'
        % (boundaries.size, ', '.join('%.17g' % v for v in boundaries)),
        'static const double OUR_PREM_C[%d][4] = {' % coefficients.shape[0],
    ]
    for row in coefficients:
        lines.append('    {%s},' % ', '.join('%.17g' % v for v in row))
    lines += [
        '};',
        '',
        '// searchsorted(B, r, side="left"), then Horner in x = r/R_E,',
        '// which is what density_prem does.',
        'static inline double our_prem_rho(double r)',
        '{',
        '    if (r > OUR_EARTH_RADIUS) r = OUR_EARTH_RADIUS;',
        '    int k = 0;',
        '    while (k < OUR_PREM_NB && OUR_PREM_B[k] < r) k++;',
        '    const double x = r / OUR_EARTH_RADIUS;',
        '    const double *a = OUR_PREM_C[k];',
        '    return a[0] + x*(a[1] + x*(a[2] + x*a[3]));',
        '}',
        '',
        '#endif',
        '',
    ]
    print('\n'.join(lines))


if __name__ == '__main__':
    main()
